"""empty message

Revision ID: 97cd625e46f4
Revises: 
Create Date: 2021-05-15 23:26:39.294679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cd625e46f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_titanic',
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=32), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('fare', sa.Float(), nullable=True),
    sa.Column('embarked', sa.VARCHAR(length=32), nullable=True),
    sa.Column('pclass', sa.VARCHAR(length=32), nullable=True),
    sa.Column('survived', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('passenger_id')
    )
    op.create_table('titanic',
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('fare', sa.Float(), nullable=True),
    sa.Column('embarked', sa.String(), nullable=True),
    sa.Column('pclass', sa.String(), nullable=True),
    sa.Column('survived', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('passenger_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titanic')
    op.drop_table('edit_titanic')
    # ### end Alembic commands ###
